import matplotlib
from flask import request, send_file, Blueprint
from docx import Document
from docx.shared import Inches
from collections import defaultdict
import io
from model.data.LoggerService import LoggerService
from model.database import DatabaseEngine

matplotlib.use("Agg")
import matplotlib.pyplot as plt

report_bp = Blueprint("report_bp", __name__, url_prefix="/api")
db_engine = DatabaseEngine()
logger = LoggerService(db_engine)


@report_bp.route("/report", methods=["POST"])
def generate_report():
    data = request.json
    user = data.get("user", {})
    _data = data.get("medianData", [])

    model_name = None
    model_version = None

    if _data:
        model_name = _data[0].get("ModelName")
        model_version = _data[0].get("ModelVersion")
    user_id = user.get("Id")
    username = user.get("Username", "Unknown")
    user_fullname = data.get("user", {}).get("FullName", "Unknown User")
    if hasattr(user, "to_dict"):
        user_fullname = user.to_dict()
    document = Document()
    document.add_heading("Dashboard Report", level=0)
    document.add_paragraph(f"Generated by: {user_fullname}")
    document.add_paragraph(f"Model: {model_name}")
    document.add_paragraph(f"Model version: {model_version}")
    # document.add_paragraph(f"Period: {data.get('period', 'Not specified')}")
    document.add_paragraph(f"Tax Type: {data.get('filters', {}).get('taxType', 'Not specified')}")
    document.add_paragraph(f"INN: {data.get('filters', {}).get('inn', 'Not specified')}")
    years = defaultdict(list)
    for row in data.get("medianData", []):
        years[row.get("Year")].append(row)
    for year, rows in sorted(years.items()):
        document.add_heading(f"Year {year}", level=1)
        table = document.add_table(rows=1, cols=4)
        table.style = "Table Grid"
        hdr = table.rows[0].cells
        hdr[0].text = "Month"
        hdr[1].text = "Income"
        hdr[2].text = "Tax"
        hdr[3].text = "Transactions"
        months = []
        incomes = []
        taxes = []
        transactions = []
        rows = sorted(rows, key=lambda x: x.get("Month", 0))
        for row in rows:
            month = row.get("Month")
            income = row.get("Income")
            tax = row.get("Tax")
            trans = row.get("Transactions")
            cells = table.add_row().cells
            cells[0].text = str(month)
            cells[1].text = f"{income:,.2f}"
            cells[2].text = f"{tax:,.2f}"
            cells[3].text = str(trans)
            months.append(month)
            incomes.append(income)
            taxes.append(tax)
            transactions.append(trans)
        document.add_paragraph("")
        plt.figure()
        plt.plot(months, incomes, label="Income")
        plt.plot(months, taxes, label="Tax")
        plt.plot(months, transactions, label="Transactions")
        plt.title(f"Year {year} Statistics")
        plt.xlabel("Month")
        plt.legend()
        img_stream = io.BytesIO()
        plt.savefig(img_stream)
        plt.close()
        img_stream.seek(0)
        document.add_picture(img_stream, width=Inches(6))
    buffer = io.BytesIO()
    document.save(buffer)
    buffer.seek(0)
    logger.log_action(
        user_id=user_id,
        username=username,
        action="Generate Report",
        additional_info=f"User {username} generated dashboard report. Model: {model_name}. Model version: {model_version}."
    )
    return send_file(
        buffer,
        as_attachment=True,
        download_name="report.docx"
    )
